handlers:
  email_confirmation:
    label: 'Courriel de confirmation'
    settings:
      from_name: défaut
      subject: défaut
  email_notification:
    label: 'Notification par courriel'
    settings:
      subject: défaut
