display:
  default:
    display_title: Master
    display_options:
      exposed_form:
        options:
          submit_button: Anwenden
          reset_button_label: Zurücksetzen
          exposed_sorts_label: 'Sortieren nach'
          sort_asc_label: Aufsteigend
          sort_desc_label: Absteigend
          text_input_required: 'Fügen Sie Text hinzu und klicken Sie auf Anwenden um Ergebnisse anzuzeigen.'
      pager:
        options:
          expose:
            items_per_page_label: 'Elemente pro Seite'
            items_per_page_options_all_label: '- Alle -'
            offset_label: Offset
          tags:
            previous: ‹‹
            next: ››
      fields:
        text:
          separator: ', '
  page_1:
    display_title: Seite
