label: Inhalt
display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: Filter
          reset_button_label: Zurücksetzen
          exposed_sorts_label: 'Sortieren nach'
          sort_asc_label: Aufsteigend
          sort_desc_label: Absteigend
      fields:
        title:
          label: Titel
        type:
          label: Inhaltstyp
          separator: ', '
        name:
          label: Autor
        status:
          label: Status
          settings:
            format_custom_true: Veröffentlicht
        changed:
          label: Aktualisiert
        operations:
          label: Operationen
      filters:
        title:
          expose:
            label: Titel
        type:
          expose:
            label: Inhaltstyp
        status:
          expose:
            label: Status
          group_info:
            group_items:
              1:
                title: Veröffentlicht
        langcode:
          expose:
            label: Sprache
      title: Inhalt
    display_title: Master
  page_1:
    display_options:
      menu:
        title: Inhalt
      tab_options:
        title: Inhalt
    display_title: Seite
