handlers:
  email_notification:
    settings:
      subject: Standardeinstellung
      body: Standardeinstellung
  email_reminder:
    settings:
      from_name: Standardeinstellung
      body: Standardeinstellung
