ignored_config_entities:
  0: moteur_calcul.parameterstable
  2: general_config.config
  4: core.menu.static_menu_link_overrides
_core:
  default_config_hash: UVH1aJ4b44UM-VdPVN7hNNuuVqfReJxwfVeDQH1Hvsk
langcode: fr
