moteur_calcul: null
_core:
  default_config_hash: t4LOY0b3_P30qj7F4qNm3vKCGIKtWKhIAcWvupcqoQE
langcode: fr
montant_pass: '39228'
tranche_1_min: '0'
tranche_1_max: '1'
tranche_2_min: '1'
tranche_2_max: '4'
tranche_3_min: '4'
tranche_3_max: '10000000'
taux_charges_sociales_tranche_1: '22.86'
taux_charges_sociales_tranche_2: '20.51'
taux_charges_sociales_tranche_3: '18.25'
nombre_jours_travailles: '365'
allocation_brute_ple_regle1_sjr: '40.4'
allocation_brute_ple_regle1_fixe: '11.84'
allocation_brute_ple_regle2_sjr: '57'
allocation_quotidienne: '28.86'
plafond_indemnites_ple_1: '75'
plafond_indemnites_ple_2: '245.04'
taux_charges_sociales_fixe: '9.7'
simulateur_encart_informatif_titre: 'MADP vous informe'
simulateur_encart_informatif_text:
  value: '<p>Votre age nous permet de déterminer ...</p><p>Votre salaire annuel brut référence:<br />vos salaires bruts mensuels perçus au cours des 12<br />dernniers mois, primes comprises mais hors indemnités<br />liées à la rupture de votre contrat.</p><p>Pour être éligible vous devez<br />- Avoir au moins 25 ans&nbsp;</p><p>- Avoir un salaire minimum de 35 000€ et qui est fonction&nbsp;</p>'
  format: basic_html
field_salaire_annuel_brut_info: 'Votre salaire est annuel brut et calculé sur la base de votre salaire mensuel brut bla bla bla'
allocation_quotidienne_minimum: '28.86'
plafond_salaire_indeminise_madp: '50'
plafond_quotidien_indeminise_madp: '300'
indemnite_mensuelle_minimum_madp: '500'
hauteur_des_pas: '50'
duree_indemnisation_minimum: '6'
duree_indemnisation_maximum: '12'
age_inferieur_25: 'âge inférieur à 25 ans'
message_age_inferieur_25: 'âge inférieur à 25 ans'
message_age_superieur_54: 'âge supérieur à 54 ans'
message_salaire_inferieur: 'Votre manque à gagner en cas de chômage n’est pas assez important pour mettre en place une garantie'
message_salaire_superieur: 'salaire supérieur à 8*PASS'
'tranche_indemnisation_1_min tranche': null
tranche_indemnisation_1_max: '3000'
tranche_indemnisation_1_augmentation: '0'
tranche_indemnisation_1_min: '0'
tranche_indemnisation_2_min: '3000'
tranche_indemnisation_2_max: '6000'
tranche_indemnisation_2_augmentation: '4'
tranche_indemnisation_3_min: '6000'
tranche_indemnisation_3_max: '9000'
tranche_indemnisation_3_augmentation: '4'
taux_cotisation_1: '5.6'
taux_cotisation_params_json: '[{"age_range":"25;49","augmentation":0,"taux_tr1":5.6,"taux_tr2":5.824,"taux_tr3":6.057},{"age_range":"50;50","augmentation":2,"taux_tr1":5.712,"taux_tr2":5.9405,"taux_tr3":6.1781},{"age_range":"51;51","augmentation":2,"taux_tr1":5.8262,"taux_tr2":6.0593,"taux_tr3":6.3017},{"age_range":"52;52","augmentation":2,"taux_tr1":5.9427,"taux_tr2":6.1804,"taux_tr3":6.4277},{"age_range":"53;53","augmentation":2,"taux_tr1":6.0616,"taux_tr2":6.304,"taux_tr3":6.5562},{"age_range":"54;54","augmentation":2,"taux_tr1":6.1828,"taux_tr2":6.4301,"taux_tr3":6.6874},{"age_range":"55;55","augmentation":4,"taux_tr1":6.4301,"taux_tr2":6.6873,"taux_tr3":6.9548},{"age_range":"56;56","augmentation":4,"taux_tr1":6.6873,"taux_tr2":6.9548,"taux_tr3":7.233},{"age_range":"57;57","augmentation":4,"taux_tr1":6.9548,"taux_tr2":7.233,"taux_tr3":7.5223},{"age_range":"58;58","augmentation":4,"taux_tr1":7.233,"taux_tr2":7.5223,"taux_tr3":7.8232},{"age_range":"59;59","augmentation":4,"taux_tr1":7.5223,"taux_tr2":7.8232,"taux_tr3":8.1361}]'
duree_indemnisation_default: '9'
limit_age_inferieur: '25'
message_age_inferieur: 'Age inférieur à 25 ans'
limit_age_superieur: '54'
limit_salaire_inferieur: '35000'
limit_salaire_superieur: '50'
message_age_superieur: 'Age supérieur à 54'
montant_mensuel_indemnise_info: "Ce montant est à titre indicatif, il pourra varier\r\nen fonction des indemnités reçues de la part de Pôle Emploi"
duree_indemnisation_montant_cotisations_info: 'La durée d''indemnisation va faire varier le montant des cotisations bla bla'
nombre_jours_travailles_pole_emploi: '261'
coef_passage_annee_pole_emploi: '1.4'
nombre_jours_travailles_madp: '365'
allocation_ple_inf_are: '40.4'
allocation_ple_partie_fixe: '11.84'
allocation_ple_sup_are: '57'
allocation_ple_are_min: '28.86'
allocation_ple_are_max: '49'
taux_charges_sociales_avec_frais_ple: '6.58275'
allocation_ple_sup_sjr: '75'
allocation_ple_plafond_are: '245.04'
taux_de_retraite: '3'
